CREATE TABLE IF NOT EXISTS inventories
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plu          VARCHAR(30)    NOT NULL DEFAULT 0,
    unit_id      SMALLINT       NOT NULL DEFAULT 0,
    multiplier   INT            NOT NULL DEFAULT 0,
    stock        INT            NOT NULL DEFAULT 0,
    price        NUMERIC(10, 2) NOT NULL DEFAULT 0,
    member_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    purchase     NUMERIC(10, 2) NOT NULL DEFAULT 0,
    discount     NUMERIC(10, 2) NOT NULL DEFAULT 0,
    create_time  TIMESTAMP      NOT NULL DEFAULT NOW(),
    update_time  TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS inventory_plu_unit_idx ON inventories (plu, unit_id);