CREATE TABLE IF NOT EXISTS product_sales_stats_daily
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_sold   DATE   NOT NULL,
    plu         VARCHAR(30),
    total_sold  BIGINT NOT NULL DEFAULT 0,
    update_time TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS date_sold_plu_idx ON product_sales_stats_daily (date_sold, plu);