CREATE TABLE IF NOT EXISTS sales_detail
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plu         VARCHAR(30)    NOT NULL,
    name        VARCHAR(255)   NOT NULL,
    unit_name   VARCHAR(30)    NOT NULL,
    barcode     VARCHAR(30)    NOT NULL,
    ppn         BOOLEAN        NOT NULL DEFAULT FALSE,
    qty         BIGINT         NOT NULL DEFAULT 0,
    price       NUMERIC(10, 2) NOT NULL DEFAULT 0,
    purchase    NUMERIC(10, 2) NOT NULL DEFAULT 0,
    discount    NUMERIC(10, 2) NOT NULL DEFAULT 0,
    create_time TIMESTAMP      NOT NULL DEFAULT NOW(),
    update_time TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS sales_detail_plu_idx ON sales_detail (plu);
CREATE UNIQUE INDEX IF NOT EXISTS sales_detail_barcode_idx ON sales_detail (barcode);
CREATE UNIQUE INDEX IF NOT EXISTS sales_detail_create_time_idx ON sales_detail ((create_time::DATE));